### PR TITLE
12.19 beta release

### PR DESCRIPTION
**Pull request by mishravinod202**
Added a new transaction type: Deposit Transaction Reversal
Added a new transaction type: Refund Transaction Reversal
Added an optional element OrderID in Capture Transaction
Added an optional element OrderID in Credit Transaction
Removed existing transaction Transaction Reversal

### CODE REVIEW

**Comment by zxc8027** [comment]
*Handling on behalf of Vivek Chouhan.*

Currently, 1 test fails when run in Jenkins.
https://armada1.litle.com:9001/view/SDKs/job/java_sdk_v12/1073/console

This appears to be due to the removal of `transactionReversalResponse` and a test that checked for it to exist no longer being valid. Either removing the test or modifying it to check for `depositTransactionReversalResponse`, `refundTransactionReversalResponse`, or both should fix it.
https://github.com/mishravinod202/cnp-sdk-for-java/blob/4b6741242033047ad1b6c947d3f29abd3e4239c2/src/test/java/com/cnp/sdk/TestResponseFileParser.java#L26

**Comment by mishravinod202** [comment]
@zxc8027 - Test has been fixed. Removed test for `transactionReversalResponse` & added tests for `depositTransactionReversalResponse` and `refundTransactionReversalResponse`

**Comment by zxc8027** [comment]
The test is now valid and the tests without the batch requests pass.
https://armada1.litle.com:9001/view/SDKs/job/java_sdk_v12/1074/console

However, the new batch tests pass. Vivek said he will take a look to get them to pass.
https://armada1.litle.com:9001/view/SDKs/job/java_sdk_v12/1075/console

**Comment by vishal4393** [comment]
As JCenter has decided not to support new package and version , we are planning to push the latest version of the SDK to MavenCentral by 15th September, 2021 .

**Pull request merged**
